### ISSUE TITLE
Discord and email are both broken

### ISSUE THREAD

**Issue by dylanrush** [ProjectDonetsk/Donetsk#22]
[support@donetsk.live](mailto:support@donetsk.live) - this is undeliverable
 https://discord.gg/donetsk - this fails in Discord, says it's an invalid invitation

**Comment by walkthestars** [comment]
donetsk discord link is defunct due to lack of boosts.
i can't speak for the email, i don't control that. zero does.

**Comment by ZEROPOINTBRUH** [comment]
Please leave relative issues about the discord server, dlls, executables, donetsk provided software @ https://support.donetsk.live
Please forward any complaints you have about the email to wegj1@hotmail.com
